## Installing Numpy

In [1]:
#!pip install numpy

## Forming lists with various int elements 

In [2]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [3]:
w1, w2, w3 = 0.3, 0.2, 0.5

## Importing Numpy Library into the notebook

In [4]:
import numpy as np

## Converting the lists into array using np.array()

In [5]:
kanto = np.array([73, 67, 43])
kanto

array([73, 67, 43])

In [6]:
weights= np.array([0.3,0.2, 0.5])
weights

array([0.3, 0.2, 0.5])

In [7]:
weights [2]

0.5

In [8]:
kanto[2]

43

## OPERATION ON ARRAYS

In [9]:
(kanto*weights).sum()

56.8

In [10]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [11]:
weights.dtype

dtype('float64')

## Multiplying in numpy

In [12]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [13]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

## Complex operations

In [14]:
data = np.array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [15]:
data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [16]:
data @ weights 

array([72.2, 59.7, 65.2, 71.1, 80.7, 73.4])

In [17]:
yeilds = data @ weights

In [18]:
yeilds

array([72.2, 59.7, 65.2, 71.1, 80.7, 73.4])

## Concatenating the yields in top the data matrix

In [19]:
data_result = np.concatenate((data,yeilds.reshape(6,1)), axis=1)

In [20]:
data_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [21]:
result= np.split (data_result, 2)
result

[array([[25. , 76. , 99. , 72.2],
        [39. , 65. , 70. , 59.7],
        [59. , 45. , 77. , 65.2]]),
 array([[99. , 62. , 58. , 71.1],
        [70. , 71. , 91. , 80.7],
        [92. , 39. , 76. , 73.4]])]

In [22]:
result1= np.split (data_result, 2, axis = 1)
result1

[array([[25., 76.],
        [39., 65.],
        [59., 45.],
        [99., 62.],
        [70., 71.],
        [92., 39.]]),
 array([[99. , 72.2],
        [70. , 59.7],
        [77. , 65.2],
        [58. , 71.1],
        [91. , 80.7],
        [76. , 73.4]])]

In [23]:
data+ weights

array([[25.3, 76.2, 99.5],
       [39.3, 65.2, 70.5],
       [59.3, 45.2, 77.5],
       [99.3, 62.2, 58.5],
       [70.3, 71.2, 91.5],
       [92.3, 39.2, 76.5]])

In [24]:
(data+weights).shape

(6, 3)

In [25]:
(data+weights).dtype

dtype('float64')

In [26]:
(data == weights).sum()

0

## Slicing an 3-D Array

In [27]:
data1 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19, 43]]])
data1

array([[[11, 12, 13, 14],
        [13, 14, 15, 19]],

       [[15, 16, 17, 21],
        [63, 92, 36, 18]],

       [[98, 32, 81, 23],
        [17, 18, 19, 43]]])

In [28]:
data1.shape

(3, 2, 4)

In [29]:
data1[1,1,1]

92

In [30]:
data1[1: , 1: , 1:]

array([[[92, 36, 18]],

       [[18, 19, 43]]])

## Array types using Numpy

In [31]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.randn(2,3)

array([[-0.61607471,  0.27715884,  0.7056633 ],
       [-0.76360705,  1.53269256, -0.16634548]])

In [34]:
np.full([2,2],20)

array([[20, 20],
       [20, 20]])